# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25fcdd11e52a4e9ecfe23d7667c9863eddcede8d501f7ec30a16d93e3c89ee63954fcc3dbc060e080c74b80eb08499b75272f44c7c7c2d254fe1f0e600ab4ab8

test:
  secret_key_base: 6b334a3c7afc0324a03b10124f870c969f2a70b07500894cdb85bc9999738578aa1981de0bc9c2b6d3864c71a3aec4c99c147dbd1d7cb8f908f52b0e42622f66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 84d6a94b5692116c3f3f70227034e4b365d7503669b55323a16a3a25400dfb5ff95c51e54172ed5ccf893748f0c9f32fb59de80a276442fa1485786331e1643e
